services:
  # 1. API Gateway Service (Single Entry Point / YARP Reverse Proxy)
  v-eval-gateway:
    build:
      context: .
      dockerfile: ./All Services/V-Eval-Gateway/Dockerfile
    container_name: v_eval_gateway
    ports:
      - "5212:5212"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
    networks:
      - veval_network

  # 2. AI Engine Service (PDF Parser, Gemini OCR, Socratic AI Tutor)
  v-eval-ai-engine:
    build:
      context: .
      dockerfile: ./All Services/V-Eval-Ai_Engine/Dockerfile
    container_name: v_eval_ai_engine
    ports:
      - "5104:5104"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
    networks:
      - veval_network

  # 3. Content Service (Question Bank, Exams, Materials & Supabase Storage)
  v-eval-content-service:
    build:
      context: .
      dockerfile: ./All Services/V-Eval-Content_Service/Dockerfile
    container_name: v_eval_content_service
    ports:
      - "5249:5249"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
    networks:
      - veval_network

  # 4. Identity Service (Authentication, JWT Token, User Management)
  v-eval-identity-service:
    build:
      context: .
      dockerfile: ./All Services/V-Eval-Identity_Service/Dockerfile
    container_name: v_eval_identity_service
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
    networks:
      - veval_network

  # 5. Practice Service (Online Examination, Auto-Grading & Competency Tracking)
  v-eval-practice-service:
    build:
      context: .
      dockerfile: ./All Services/V-Eval-Practice_Service/Dockerfile
    container_name: v_eval_practice_service
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
    networks:
      - veval_network

networks:
  veval_network:
    driver: bridge
